# $Id: Makefile,v 1.4 2009-12-13 12:04:18 cnvogelg Exp $

RELATIVEPATH=../
include ${RELATIVEPATH}LINUX/config.make

PROG = cbmrpm41
INC  = cbmrpm41.inc

LINK_FLAGS += -lm

include ${RELATIVEPATH}LINUX/prgrules.make
