.\" Copied from the OpenCBM Users Guide, written by:
.\"   Michael Klein <nip@c64.org>
.\"   Spiro Trikaliotis <cbm4win@trikaliotis.net>
.\"   Wolfgang Moser <d81.de>
.\"
.\" Converted to nroff by:
.\"   Frédéric Brière <fbriere@fbriere.net>
.\"
.TH CBMFORMAT "1" "2008-02-10" "OpenCBM 0.4.2" "User Commands"
.SH NAME
cbmformat \- fast low-level disk formatter for CBM drives
.SH SYNOPSIS
.B cbmformat
.RI [ options ]
.I drive
.IR name , ID
.SH DESCRIPTION
.B cbmformat
is a fast low-level disk formatter for the 1541 and compatible devices
(1570, 1571, third-party clones).
A 1581 drive is not supported.
.PP
.I drive
has to be the drive number of the disk drive,
.I name
is a name with up to 16 characters which will be the name of the disk
after formatting,
.I ID
is the 2-letter disk ID.
.PP
Note: Unlike the N0 command of the drive, the ID must be given (thus,
no so-called "short format" is possible).
.SH OPTIONS
.TP
\fB\-c\fP, \fB\-\-clear\fP
Clear (demagnetize) this disk.
This is highly recommended if the disk is used for the first time, or
if it was previously formatted for another system (i.e., MS-DOS).
Note that this option takes much time.
.TP
\fB\-n\fP, \fB\-\-no\-bump\fP
Do not bump drive head at the beginning.
Don't use this on eventually misaligned drives.
.TP
\fB\-o\fP, \fB\-\-original\fP
Fill sectors with the original pattern (0x4b, 0x01, 0x01...) instead
of zeroes.
The original pattern is probably due to a bug in the drive ROM, apart
from this, zeroing out unused sectors should give (slightly) better
results for compressed disk images.
.TP
\fB\-p\fP, \fB\-\-progress\fP
Display a hash mark (`#') for each formatted track.
Slows formatting down a bit.
.TP
\fB\-s\fP, \fB\-\-status\fP
Display drive status after formatting.
Normally,
.B cbmformat
exits after executing the drive code.
With this option turned on,
.B cbmformat
waits until the drive has finished formatting and prints the drive
status after initializing the BAM on standard out.
.TP
\fB\-v\fP, \fB\-\-verify\fP
Verify each track after it is written.
As this needs an extra round of the drive for each track, the formatting
time is almost doubled.
.TP
\fB\-x\fP, \fB\-\-extended\fP
Format a 40 track disk, the BAM format is compatible to SpeedDOS.
.PP
.TP
\fB\-h\fP, \fB\-\-help\fP
Display help and exit.
.TP
\fB\-V\fP, \fB\-\-version\fP
Display version information and exit.
.SH NOTES
We encountered problems with decent revision/mechanics combinations of
the 1571 disk drives when using
.BR cbmformat .
We highly recommend to use
.B \-\-original
and
.B \-\-verify
with 1571 drives.
From our experience, with
.BR \-\-original ,
the problem does not occur; with
.BR \-\-verify ,
the drive tests each track after it was formatted and ensures that the
failure condition did not occur.
.PP
We did not encounter these problems with either of 1541 (1541-II, 1541C),
1570 or 1571CR (the drive which is part of the C128DCR) drives, only with
original 1571 drives.
.PP
In the current state,
.B cbmformat
is not able to format double-sided disks on a 1571 drive.
.SH EXAMPLES
Format standard disk (35 tracks) in drive 8:
.RS
.PP
cbmformat 8 GAMES,42
.RE
.PP
Format standard disk (35 tracks) in drive 9, use (buggy) 1541 sector
pattern (for example, because this is a 1571 drive), show drive status
when done:
.RS
.PP
cbmformat \-os 9 1571disk,71
.RE
.PP
SpeedDOS disk (40 tracks), show progress indicator, all sectors zeroed
out, no head banging:
.RS
.PP
cbmformat \-npx 8 "40 TRACKS,OK"
.RE
.SH SEE ALSO
.BR cbmforng (1),
.BR cbmctrl (1)
