# $Id: Makefile,v 1.4 2009-12-13 12:04:18 cnvogelg Exp $

RELATIVEPATH=../
include ${RELATIVEPATH}LINUX/config.make

OBJS = main.o pc64.o t64.o raw.o
PROG = cbmcopy
LINKS = cbmread cbmwrite

include ${RELATIVEPATH}LINUX/prgrules.make
