.\" Copied from the OpenCBM Users Guide, written by:
.\"   Michael Klein <nip@c64.org>
.\"   Spiro Trikaliotis <cbm4win@trikaliotis.net>
.\"   Wolfgang Moser <d81.de>
.\"
.\" Converted to nroff by:
.\"   Frédéric Brière <fbriere@fbriere.net>
.\"
.TH D64COPY "1" "2008-02-10" "OpenCBM 0.4.2" "User Commands"
.SH NAME
d64copy \- fast disk image transfer program for CBM drives
.SH SYNOPSIS
.B d64copy
.RI [ options ]
.I source
.I target
.SH DESCRIPTION
.B d64copy
is a fast disk image transfer (both read and write) program for the 1541
and compatible devices (1570, 1571, third-party clones).
A 1581 drive is not supported.
.PP
Either
.I source
or
.I target
must be an external drive, valid names are 8, 9, 10 and 11.
The other parameter specifies the file name of the .d64 image.
.SH OPTIONS
.TP
\fB\-q\fP, \fB\-\-quiet\fP
Quiet output, fewer messages (also suppresses warnings, should not be used)
.TP
\fB\-v\fP, \fB\-\-verbose\fP
Verbose output, more messages (can be repeated)
.TP
\fB\-n\fP, \fB\-\-no\-progress\fP
Omit progress display
.PP
.TP
\fB\-2\fP, \fB\-\-two\-sided\fP
Double-sided mode for copying .d71 images to/from a 1571 drive.
Warp mode is not supported (yet).
.TP
\fB\-b\fP, \fB\-\-bam\-only\fP
BAM-only copy.
Only blocks marked as allocated are copied.
For extended tracks (36-40), SpeedDOS BAM format is assumed.
Use with caution, at least one wide-spread directory editor tends to
forget to allocate some
directory blocks.
.TP
\fB\-B\fP, \fB\-\-bam\-save\fP
Safe BAM-only copy.
This is like the
.B \-b
option but always copies the entire directory track (18, 18 and 53 in
double-sided mode).
.TP
\fB\-d\fP, \fB\-\-drive\-type\fP=\fItype\fP
Skip drive type detection.
0 or 1541 specifies 1541 mode (1 MHz, parallel cable at VIA $1800),
1 or 1571 forces 1571 mode (2 MHz, parallel cable at CIA $4000).
.TP
\fB\-E\fP, \fB\-\-error\-mode\fP=\fImode\fP
Controls whether error is appended to the disk image (15x1\(->PC only).
Allowed values for mode are (abbreviations allowed):
.PP
.RS
.RS
.PD 0
.IP \(bu 2
.B always
.IP \(bu 2
.B on_error
(default)
.IP \(bu 2
.B never
.PD
.RE
.RE
.TP
\fB\-i\fP, \fB\-\-interleave\fP=\fIvalue\fP
Set interleave value.
This is ignored when reading in warp mode.
Default is 16 for transfer mode
.BR original ,
for
.B turbo
and
.B warp
write as follows:
.sp
.TS
tab (|);
c c c
l c c.
|turbo (r/w)|warp (write only)
serial1|3|5
serial2|12|11
parallel|6|3
.TE
.IP ""
Lower values might slightly reduce transfer times, but if set a bit too
low, transfer times will dramatically increase.
.TP
\fB\-r\fP, \fB\-\-retry\-count\fP=\fIcount\fP
Number of retries.
.TP
\fB\-s\fP, \fB\-\-start\-track\fP=\fItrack\fP
Set start track (defaults to 1)
.TP
\fB\-e\fP, \fB\-\-end\-track\fP=\fItrack\fP
Set end track (default is 35 for .d64 images, 70 for .d71 images).
.B d64copy
is able to access tracks 1-35 in
.B original
transfer mode and 1-42 with
.BR serial1 ,
.B serial2
and
.BR parallel .
The 1571 supports tracks 1-70 in double sided (.d71) mode.
.TP
\fB\-t\fP, \fB\-\-transfer\fP=\fImode\fP
Set transfer mode.
Valid modes are:
.PP
.RS
.RS
.PD 0
.IP \(bu 2
.B auto
(default)
.IP \(bu
.B original
(slowest)
.IP \(bu
.B serial1
.IP \(bu
.B serial2
.IP \(bu
.B parallel
(fastest)
.PD
.RE
.RE
.IP ""
.B original
and
.B serial1
should work in any case.
.B serial2
won't work with more than one device connected to the IEC bus,
.B parallel
requires an additional XP1541/XP1571 cable.
.IP ""
If
.B auto
is used,
.B d64copy
itself determines the best transfer mode usable with the current setup,
and uses that one.
Thus, you will seldom want to manually overdrive the transfer mode option.
.TP
\fB\-w\fP, \fB\-\-warp\fP
Enable warp mode.
This is default now; this option is only supported for
backward-compatibility with OpenCBM (cbm4linux/cbm4win) versions
before 0.4.0.
.TP
\fB\-\-no\-warp\fP
Disable warp mode.
Warp mode is usually a good idea for transferring disk images unless you
have a very slow CPU and/or bad disk material.
Warp mode sends raw GCR data over the bus, which assures data integrity
on the PC side and relieves the drive's CPU.
Thus, it is unlikely you will want to use that option.
.PP
.TP
\fB\-h\fP, \fB\-\-help\fP
Display help and exit.
.TP
\fB\-V\fP, \fB\-\-version\fP
Display version information and exit.
.SH EXAMPLES
Read a D64 disk image from the floppy in drive 8 to the file image.d64,
automatically selecting the fastest transfer method:
.RS
.PP
d64copy 8 image.d64
.RE
.PP
Copy the D64 disk image in image.d64 to the floppy in drive 9,
automatically selecting the fastest transfer method:
.RS
.PP
d64copy image.d64 9
.RE
.PP
Copy a double-sided disk from a 1571 drive 9 to image.d71, using
.B serial1
transfer method and only reading the blocks which are marked as used in
the BAM:
.RS
.PP
d64copy \-2 \-B \-\-transfer=serial1 9 image.d64
.RE
.SH SEE ALSO
.BR cbmcopy (1),
.BR cbmctrl (1)
