#
# Makefile.xmingw
#

XMINGW_ROOT = /usr/local/cross-tools/bin

CC = $(XMINGW_ROOT)/i386-mingw32msvc-gcc
CFLAGS+=-DWIN -Wall
LFLAGS+=-lusb

APP = xu1541_update
OBJS = xu1541_update.o ihex.o flash.o

all: ../$(APP).exe

clean:
	rm -f ../$(APP).exe *.o

../$(APP).exe: $(OBJS)
	$(CC) $(OBJS) -o $@ $(LFLAGS)
