Source: cbm4linux
Section: misc
Priority: extra
Build-Depends: debhelper (>= 3.0.0)
Maintainer: Michael Klein <michael(dot)klein(at)puffin(dot)lb(dot)shuttle(dot)de>
Standards-Version: 3.7.2.1

Package: cbm4linux-module-KERNEL_VERSION
Provides: cbm4linux-module
Architecture: i386
Section: misc
Description: Driver module for the Commodore serial IEC bus
 This driver provides access to serial IEC devices (C=1541 etc.)
 .
 This package contains the cbm module for compiled for kernel version
 KERNEL_VERSION.
