#define CBM4WIN_VERSION_MAJOR     0
#define CBM4WIN_VERSION_MINOR     1
#define CBM4WIN_VERSION_SUBMINOR  0
#define CBM4WIN_VERSION_BUGFIX    0
#define CBM4WIN_VERSION_DEVEL     26

#define CBM4WIN_VERSION_STRING   "0.1.0.26"
