.\" Copied from the OpenCBM Users Guide, written by:
.\"   Michael Klein <nip@c64.org>
.\"   Spiro Trikaliotis <cbm4win@trikaliotis.net>
.\"   Wolfgang Moser <d81.de>
.\"
.\" Converted to nroff by:
.\"   Frédéric Brière <fbriere@fbriere.net>
.\"
.TH CBMCOPY "1" "2008-02-10" "OpenCBM 0.4.2" "User Commands"
.SH NAME
cbmcopy \- fast file transfer program for CBM drives
.SH SYNOPSIS
.B cbmcopy
.RI [ options ]
.RB { \-\-read | \-\-write }
.B drive
.B files
.PP
.B cbmread
.RI [ options ]
.B drive
.B files
.PP
.B cbmwrite
.RI [ options ]
.B drive
.B files
.SH DESCRIPTION
.B cbmcopy
is a fast file transfer program for various disk drives, in particular
the 1541, 1570, 1571 and 1581 devices.
.PP
.I drive
specifies the drive number for file copy.
The remaining arguments specify the files to be sent to/read from the
disk drive.
This version supports Raw, PC64 (P00) and T64 files.
They are recognized when sending files to the disk drive, files read
from external devices are always stored as raw binary data.
.SH OPTIONS
.TP
\fB\-q\fP, \fB\-\-quiet\fP
Quiet output, fewer messages (also suppresses warnings, should not be used)
.TP
\fB\-v\fP, \fB\-\-verbose\fP
Verbose output, more messages (can be repeated)
.TP
\fB\-n\fP, \fB\-\-no\-progress\fP
Omit progress display
.PP
.TP
\fB\-r\fP, \fB\-\-read\fP
Operate in read-mode, i.e. read data from an external device.
Starting
.B cbmcopy
as
.B cbmread
has the same effect.
.TP
\fB\-w\fP, \fB\-\-write\fP
Operate in write-mode, i.e. send files to an external device.
Starting
.B cbmcopy
as
.B cbmwrite
has the same effect.
.PP
.TP
\fB\-a\fP, \fB\-\-address\fP=\fIaddress\fP
Overrides the file's first two bytes with
.IR address .
.TP
\fB\-d\fP, \fB\-\-drive\-type\fP=\fItype\fP
Skip drive type detection.
Valid types are 1541, 1570, 1571 and 1581.
.TP
\fB\-f\fP, \fB\-\-file\-type\fP=\fItype\fP
Specifies/overrides file type.
Supported types are
.BR P ,
.BR S ,
.BR D ,
.BR U .
Raw files default to
.BR P ,
whereas the T64 format contains meta data which includes the file type.
For PC64 files,
.B cbmwrite
tries to guess the file type from the file extension.
This option is only valid in write-mode.
.TP
\fB\-o\fP, \fB\-\-output\fP=\fIname\fP
Specifies target name.
ASCII/PetSCII conversion is performed when in write-mode.
.TP
\fB\-R\fP, \fB\-\-raw\fP
Skip file type detection.
File data is sent as is.
This option is only
valid in write-mode.
.TP
\fB\-t\fP, \fB\-\-transfer\fP=\fImode\fP
Set transfer mode.
Valid modes are:
.PP
.RS
.RS
.PD 0
.IP \(bu 2
.B auto
(default)
.IP \(bu
.B serial1
(slowest)
.IP \(bu
.B serial2
.IP \(bu
.B parallel
(fastest, not possible with a 1581)
.PD
.RE
.RE
.IP ""
.B serial1
should work in any case.
.B serial2
won't work with more than one device connected to the IEC bus,
.B parallel
requires a XP1541/XP1571 cable in addition to the XM/XA1541.
.IP ""
If
.B auto
is given, or this option is completely omitted,
.B cbmcopy
will automatically determine the fastest transfer method possible with
the current setup.
Thus, you will seldom want to manually overdrive the transfer mode
option.
.PP
.TP
\fB\-h\fP, \fB\-\-help\fP
Display help and exit.
.TP
\fB\-V\fP, \fB\-\-version\fP
Display version information and exit.
.SH EXAMPLES
Read a file called `cbmfile' from drive 8 and store its binary value
into the file `file.bin', automatically selecting the fastest transfer
method:
.PP
.RS
cbmcopy \-r 8 cbmfile \-o file.bin
.RE
.PP
Write out the file `file.p00' in P64 format to the disk in drive 9,
using
.B serial1
transfer method:
.PP
.RS
cbmcopy \-w 9 file.p00
.RE
.SH SEE ALSO
.BR d64copy (1),
.BR cbmctrl (1)
