# $Id: Makefile,v 1.5 2009-12-13 12:04:18 cnvogelg Exp $

RELATIVEPATH=../
include ${RELATIVEPATH}LINUX/config.make

PROG    = cbmctrl
INC     = tdchange.inc

include ${RELATIVEPATH}LINUX/prgrules.make
